Repository paion-data/screwdriver-marketplace, pull requests merged in 2024-05, with the labels that each got.

#2 修复 Screwdriver pipeline 运行时报错
  .gitignore
  README.md
  screwdriver.yaml
Labels: BUG, NEED 1 REVIEW

#9 Install Maven with JDK
  commands/install-jdk-with-maven-ubuntu/run.sh
  commands/install-jdk-with-maven-ubuntu/sd-command.yaml
Labels: NEED 1 REVIEW, NEW FEATURE

#4 Fix Screwdriver template for React deployment
  .github/workflows/ci-cd.yml
  templates/react-app-alicloud-sd-template.yaml
Labels: BUG, WIP

#10 Do not publish template in PR
  screwdriver.yaml
Labels: BUG, CI/CD, NEED 1 REVIEW

#11 Publish should be triggered jointly
  screwdriver.yaml
Labels: BUG, NEED 1 REVIEW

#12 Do not publish in PR
  screwdriver.yaml
Labels: BUG, CI/CD, NEED 1 REVIEW

#13 Support base64-encoded SSL Certificate
  templates/react-app-alicloud-sd-template.yaml
Labels: CI/CD, MERGEABLE

#17 Add React DNS Resolution Config in development template
  templates/react-app-alicloud-sd-template.yaml
Labels: CI/CD, CONFIG

#18 Remove maven installer
  commands/install-jdk-with-maven-ubuntu/sd-command.yaml
  commands/install-maven-ubuntu/run.sh
  commands/install-maven-ubuntu/sd-command.yaml
  screwdriver.yaml
Labels: BREAKING CHANGE, NEED 1 REVIEW, REFACTORING

#19 Implement screwdriver command that installs Docker
  commands/install-docker/run.sh
  commands/install-docker/sd-command.yaml
  screwdriver.yaml
Labels: NEED 1 REVIEW, NEW FEATURE

#21 Support EIP binding to React Intance
  templates/react-app-alicloud-sd-template.yaml
Labels: CI/CD, MERGEABLE
